parameters:
    goat.cache_dir: "%kernel.cache_dir%/goat"

services:

    goat.session:
        class: Goat\Core\Client\Session
        arguments: ["@goat.connection.readwrite", "@?goat.connection.readonly"]

    goat.converter_map:
        public: false
        class: Goat\Core\Converter\ConverterMap

    goat.hydrator_map:
        public: false
        class: Goat\Core\Hydrator\HydratorMap
        arguments: ["%goat.cache_dir%/hydrator"]
