services:

    goat.session.profiling:
        public: false
        class: Goat\Driver\Profiling\ProfilingDriverProxy
        decorates: goat.session
        arguments: ["@goat.session.profiling.inner"]

    goat.data_collector:
        class: Goat\Bundle\DataCollector\ConnectionDataCollector
        arguments: ["@goat.session.profiling", '@?debug.stopwatch']
        tags: [{ name: data_collector, template: "@Goat/Profiler/goat.html.twig", id: goat_connection}]
