parameters:
    goat.cache_dir: "%kernel.cache_dir%/goat"
    goat.mapper.class_index: []
    goat.mapper.service_index: []

services:

    goat.session.default:
        class: Goat\Driver\Session
        arguments: ["@goat.connection.readwrite", "@?goat.connection.readonly"]

    goat.session:
        alias: goat.session.default

    goat.converter_map:
        class: Goat\Converter\ConverterMap

    goat.hydrator_map:
        class: Goat\Hydrator\HydratorMap
        arguments: ["%goat.cache_dir%/hydrator"]

    goat.mapper_registry:
        public: true
        class: Goat\Bundle\Mapper\MapperRegistry
        arguments: ['@service_container', '%goat.mapper.service_index%', '%goat.mapper.class_index%']

    goat.argument_value_resolver:
        public: false
        class: Goat\Bundle\Controller\EntityValueResolver
        arguments: ['@goat.mapper_registry']
        tags: [{name: controller.argument_value_resolver, priority: 150}]

    goat.installer:
        class: Goat\Bundle\Installer\InstallManager
        arguments: ['@goat.session', '@service_container', '@event_dispatcher', [], []]

    goat.installer.self_updater:
        class: Goat\Bundle\Installer\SelfUpdater
        tags: [{name: goat.updater}]
