parameters:
    goat.cache_dir: "%kernel.cache_dir%/goat"
    goat.mapper.class_index: []
    goat.mapper.service_index: []

services:

    goat.session.default:
        class: Goat\Core\Client\Session
        arguments: ["@goat.connection.readwrite", "@?goat.connection.readonly"]

    goat.session:
        alias: goat.session.default

    goat.converter_map:
        class: Goat\Core\Converter\ConverterMap

    goat.hydrator_map:
        class: Goat\Core\Hydrator\HydratorMap
        arguments: ["%goat.cache_dir%/hydrator"]

    goat.mapper_registry:
        public: true
        class: Goat\Bundle\Mapper\MapperRegistry
        arguments: ['@service_container', '%goat.mapper.service_index%', '%goat.mapper.class_index%']
